version: '3.8'
services:
  postgres-server:
    image: postgres:14.4-alpine3.16
    environment:
      POSTGRES_DB: streaming_service_agregator
      POSTGRES_USER: app
      POSTGRES_PASSWORD: dev
    networks:
      - default
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./esquema.sql:/docker-entrypoint-initdb.d/00-esquema.sql
      - ./dados.sql:/docker-entrypoint-initdb.d/01-dados.sql

  postgres-web:
    image: sosedoff/pgweb:0.11.11
    environment:
      DATABASE_URL: postgres://app:dev@postgres-server:5432/streaming_service_agregator?sslmode=disable
    ports:
      - 127.0.0.1:8081:8081
    networks:
      - default
    restart: always

volumes:
  postgres-data:

